services:
  calibre:
    build: .
    restart: always
    volumes:
      - ./books:/data/library
    ports:
      - 8080:8080
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
