services:
  calibre:
    build: .
    restart: always
    volumes:
      - ./books:/data
      # - ./data:/config
    ports:
      - 8081:8081
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PORT=8081
      - ENABLE_AUTH=1
